# Generated by Django 4.0.1 on 2022-01-31 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museb', '0002_alter_music_main_artiste'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='museb.album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='music',
            name='main_artiste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museb.artiste'),
        ),
    ]
