# Generated by Django 4.0.1 on 2022-02-01 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museb', '0005_alter_music_album_alter_music_main_artiste'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverArtiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('trending', models.BooleanField()),
                ('collaborators', models.CharField(blank=True, max_length=100, null=True)),
                ('music_file', models.FileField(upload_to='')),
                ('streams', models.IntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='museb.album')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museb.genre')),
                ('main_artiste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museb.artiste')),
            ],
        ),
    ]
