# Generated by Django 4.0.1 on 2022-02-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museb', '0009_music_new_listenlater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='new',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
