# Generated by Django 4.0.1 on 2022-02-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museb', '0012_alter_likedmusic_collaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedmusic',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
