# Generated by Django 4.0.1 on 2022-02-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museb', '0013_likedmusic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedmusic',
            name='collaborators',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
