# Generated by Django 4.0.1 on 2022-02-21 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('museb', '0017_alter_followedartistes_user_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenlater',
            name='music',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='museb.music'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listenlater',
            name='user_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
