# Generated by Django 4.0.1 on 2022-01-31 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='main_artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museb.artiste'),
        ),
    ]
