# Generated by Django 4.0.1 on 2022-01-31 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museb', '0003_music_album_alter_music_main_artiste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='main_artiste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='museb.artiste'),
        ),
    ]
