# Generated by Django 4.0.1 on 2022-02-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('museb', '0007_alter_album_artiste'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museb.music')),
                ('user_token', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authtoken.token')),
            ],
        ),
        migrations.CreateModel(
            name='FollowedArtistes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museb.artiste')),
                ('user_token', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authtoken.token')),
            ],
        ),
    ]
