# Generated by Django 4.0.1 on 2022-02-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('museb', '0008_likedmusic_followedartistes'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='new',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='ListenLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museb.music')),
                ('user_token', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authtoken.token')),
            ],
        ),
    ]
