# Generated by Django 4.0.1 on 2022-02-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museb', '0014_alter_likedmusic_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedmusic',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='likedmusic',
            name='image',
        ),
        migrations.RemoveField(
            model_name='likedmusic',
            name='main_artiste',
        ),
        migrations.RemoveField(
            model_name='likedmusic',
            name='music_file',
        ),
        migrations.RemoveField(
            model_name='likedmusic',
            name='title',
        ),
        migrations.AddField(
            model_name='likedmusic',
            name='music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='museb.music'),
        ),
    ]
