# Generated by Django 4.0.1 on 2022-02-21 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('museb', '0015_remove_likedmusic_collaborators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenlater',
            name='user_token',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authtoken.token'),
        ),
    ]
