# Generated by Django 4.0.1 on 2022-03-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museb', '0019_remove_playlist_songs_playlist_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenlater',
            name='image',
            field=models.ImageField(default='memoji.jpg', upload_to=''),
        ),
    ]
