# Generated by Django 4.0.5 on 2022-10-03 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museb', '0021_remove_listenlater_image_userimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followedartistes',
            name='user_token',
        ),
        migrations.RemoveField(
            model_name='likedmusic',
            name='user_token',
        ),
        migrations.RemoveField(
            model_name='listenlater',
            name='user_token',
        ),
        migrations.RemoveField(
            model_name='userimage',
            name='token',
        ),
        migrations.AddField(
            model_name='followedartistes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likedmusic',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listenlater',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userimage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
