# Generated by Django 4.0.5 on 2022-10-05 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museb', '0022_remove_followedartistes_user_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
