# Generated by Django 4.0.5 on 2022-10-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museb', '0023_music_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='new',
        ),
        migrations.RemoveField(
            model_name='music',
            name='trending',
        ),
    ]
