# Generated by Django 4.0.5 on 2022-10-06 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('museb', '0024_remove_music_new_remove_music_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followedartistes',
            name='artistes',
        ),
        migrations.AddField(
            model_name='followedartistes',
            name='artistes',
            field=models.ManyToManyField(to='museb.artiste'),
        ),
        migrations.AlterField(
            model_name='followedartistes',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='likedmusic',
            name='music',
        ),
        migrations.AddField(
            model_name='likedmusic',
            name='music',
            field=models.ManyToManyField(to='museb.music'),
        ),
        migrations.AlterField(
            model_name='likedmusic',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='listenlater',
            name='music',
        ),
        migrations.AddField(
            model_name='listenlater',
            name='music',
            field=models.ManyToManyField(to='museb.music'),
        ),
        migrations.AlterField(
            model_name='listenlater',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
